import { Question, Prize } from './types';

export const QUESTIONS: Question[] = [
  // Easy: Q1-5
  {
    id: 1,
    question: 'You receive an urgent email that looks like it\'s from DHL IT, asking you to click a link to verify your login details immediately. What\'s the best next step?',
    options: ['Click the link; it\'s from IT so it must be important.', 'Reply with your password so they can verify it for you.', 'Ignore it for now, it\'s probably not urgent.', 'Delete the email and report it to the IT helpdesk as potential phishing.'],
    correctAnswer: 'Delete the email and report it to the IT helpdesk as potential phishing.',
    explanation: 'This is a classic phishing tactic. Legitimate IT departments will never ask for your password via an email link. Always report suspicious emails.',
  },
  {
    id: 2,
    question: 'Which of the following is the strongest password for your work account?',
    options: ['Password123!', 'MyDogFluffy1998', 'CorrectHorseBatteryStaple', 'The name of the company you work for.'],
    correctAnswer: 'CorrectHorseBatteryStaple',
    explanation: 'The best passwords are long phrases (passphrases) that are easy for you to remember but hard for computers to guess. Using common words or personal info is risky.',
  },
  {
    id: 3,
    question: 'You find a mysterious USB stick labeled "TOP SECRET SALARY INFO" in the breakroom. What\'s the wisest move?',
    options: ['Plug it into your computer to see whose it is. Curiosity is a virtue!', 'Ask your coworkers if it\'s theirs.', 'Take it straight to the IT/Security department without plugging it in.', 'Plug it into the shared printer to see what files are on it.'],
    correctAnswer: 'Take it straight to the IT/Security department without plugging it in.',
    explanation: 'Unknown USB drives are a common way for malware to spread. Never plug them into any company device. The security team has the tools to inspect them safely.',
  },
  {
    id: 4,
    question: 'You\'re at a coffee shop using their free Wi-Fi. Which of these activities is the riskiest?',
    options: ['Browsing the latest cat videos on YouTube.', 'Checking the weather forecast.', 'Logging into your corporate email or online banking.', 'Reading the news online.'],
    correctAnswer: 'Logging into your corporate email or online banking.',
    explanation: 'Public Wi-Fi is often not secure. Criminals can "listen in" on the connection. Avoid logging into sensitive accounts like work email or banking unless you\'re using a VPN.',
  },
  {
    id: 5,
    question: 'Your company requires you to use "Two-Factor Authentication" (2FA). What does that actually mean?',
    options: ['You have to type your password twice.', 'It\'s a password and a second code, usually from your phone.', 'You need two friends to approve your login.', 'Your computer\'s firewall has double the power.'],
    correctAnswer: 'It\'s a password and a second code, usually from your phone.',
    explanation: '2FA is like having two locks on your door. Even if a thief steals your key (password), they still can\'t get in without the second key (the code from your phone).',
  },
  // Medium: Q6-10
  {
    id: 6,
    question: 'You get a call from someone claiming to be from "Microsoft Support." They say your computer is sending error messages and need remote access to fix it. What\'s a major red flag?',
    options: ['They have a friendly and helpful tone of voice.', 'They ask for your computer\'s model number.', 'They initiated the call and are creating a sense of urgency.', 'They offer you a discount on antivirus software.'],
    correctAnswer: 'They initiated the call and are creating a sense of urgency.',
    explanation: 'Unsolicited calls from tech support are almost always scams. They use fear and urgency to trick you into giving them control of your computer. Hang up and report it.',
  },
  {
    id: 7,
    question: 'What\'s the main benefit of using a password manager?',
    options: ['It lets you use the same easy password everywhere, but securely.', 'It helps you create and remember unique, super-strong passwords for every site.', 'It automatically fills in your username but makes you type the password.', 'It shares your passwords with the IT team so they can help you faster.'],
    correctAnswer: 'It helps you create and remember unique, super-strong passwords for every site.',
    explanation: 'A password manager is like a secure vault for all your different passwords. You only need to remember one master password to unlock it, and it handles the rest.',
  },
  {
    id: 8,
    question: 'Why is a "clean desk policy" important for cybersecurity?',
    options: ['It makes the office look tidy for visitors.', 'It prevents sensitive documents with passwords or customer data from being left out.', 'It helps the cleaning staff work more efficiently.', 'It reduces paper clutter, which is good for the environment.'],
    correctAnswer: 'It prevents sensitive documents with passwords or customer data from being left out.',
    explanation: 'While a tidy desk is nice, the main security reason is to protect information. A sticky note with a password or a customer list left on a desk is an easy target for theft.',
  },
  {
    id: 9,
    question: 'A scary message pops up on your screen, locking all your files. It demands payment in Bitcoin to get them back. This is a classic case of...',
    options: ['A "computer flu."', 'Ransomware.', 'A "helpful" cleanup tool.', 'A system update.'],
    correctAnswer: 'Ransomware.',
    explanation: 'This is a ransomware attack. If this happens, disconnect your computer from the network immediately and report it to IT. Never pay the ransom!',
  },
  {
    id: 10,
    question: 'Under data privacy laws like GDPR, what does "data minimization" mean?',
    options: ['The company will use a really, really small font for its privacy policy.', 'The company should only collect the absolute minimum data needed for a specific task.', 'The company promises to minimize the number of ads you see.', 'Your data will be stored on a mini-SD card.'],
    correctAnswer: 'The company should only collect the absolute minimum data needed for a specific task.',
    explanation: 'Data minimization is a key privacy principle. It means companies shouldn\'t be greedy with your data; they should only collect what\'s truly necessary.',
  },
  // Hard: Q11-15
  {
    id: 11,
    question: 'What is considered an "insider threat"?',
    options: ['A spy from a rival company trying to hack the network.', 'An employee who accidentally clicks on a phishing link.', 'A disgruntled former employee who still has access to systems.', 'Both B and C are examples of insider threats.'],
    correctAnswer: 'Both B and C are examples of insider threats.',
    explanation: 'An insider threat isn\'t always malicious. It can be an employee making an honest mistake (unintentional) or a former/current employee acting with bad intent (malicious).',
  },
  {
    id: 12,
    question: 'You\'re logging into your laptop at a busy airport gate. What is "shoulder surfing"?',
    options: ['A cool new dance move popular with frequent flyers.', 'When someone sneakily watches over your shoulder to see you type your password.', 'A technique for getting the best view from the airplane window.', 'When you lean on a fellow passenger\'s shoulder because you\'re tired.'],
    correctAnswer: 'When someone sneakily watches over your shoulder to see you type your password.',
    explanation: 'Be aware of your surroundings! Shoulder surfing is a low-tech way to steal credentials. Use a privacy screen or shield your keyboard when in public.',
  },
  {
    id: 13,
    question: 'You realize you\'ve just clicked a bad link and might have installed malware. What is the absolute FIRST thing you should do?',
    options: ['Immediately turn off your computer to stop it.', 'Disconnect from the internet (unplug cable or turn off Wi-Fi).', 'Run a virus scan yourself to see if you can fix it.', 'Keep working and hope it goes away on its own.'],
    correctAnswer: 'Disconnect from the internet (unplug cable or turn off Wi-Fi).',
    explanation: 'Disconnecting from the network is the top priority. This contains the threat and prevents it from spreading or sending data out. Then, report it to IT immediately.',
  },
  {
    id: 14,
    question: 'You get an email from someone who looks like your CEO. It\'s marked "URGENT" and asks you to immediately wire money to a new vendor. What should you do?',
    options: ['Process the wire transfer immediately; you don\'t want to keep the CEO waiting.', 'Reply to the email to ask for confirmation.', 'Forward the request to your manager for approval.', 'Verify the request through a different channel, like a phone call.'],
    correctAnswer: 'Verify the request through a different channel, like a phone call.',
    explanation: 'This is a scam called "CEO Fraud." Scammers impersonate executives to create pressure. Always verify unusual financial requests using a different communication method.',
  },
  {
    id: 15,
    question: 'In the digital world, "non-repudiation" is a fancy term that ensures what?',
    options: ['You can\'t be fired for a security mistake.', 'A website\'s privacy policy is easy to read.', 'Someone can\'t deny having sent a message or made a transaction.', 'Your computer will never refuse to boot up.'],
    correctAnswer: 'Someone can\'t deny having sent a message or made a transaction.',
    explanation: 'Think of it like a certified signature. Digital signatures provide non-repudiation, creating an undeniable link between a person and an action, crucial for digital trust.',
  },
];

export const PRIZE_LADDER: Prize[] = [
  { level: 15, prize: '€1,000,000', title: 'Cybersecurity Millionaire', isSafeZone: false },
  { level: 14, prize: '€500,000', title: '', isSafeZone: false },
  { level: 13, prize: '€250,000', title: 'Security Champion', isSafeZone: false },
  { level: 12, prize: '€125,000', title: '', isSafeZone: false },
  { level: 11, prize: '€64,000', title: '', isSafeZone: false },
  { level: 10, prize: '€32,000', title: 'Data Defender', isSafeZone: true },
  { level: 9, prize: '€16,000', title: '', isSafeZone: false },
  { level: 8, prize: '€8,000', title: '', isSafeZone: false },
  { level: 7, prize: '€4,000', title: '', isSafeZone: false },
  { level: 6, prize: '€2,000', title: '', isSafeZone: false },
  { level: 5, prize: '€1,000', title: 'Phish Fighter', isSafeZone: true },
  { level: 4, prize: '€500', title: '', isSafeZone: false },
  { level: 3, prize: '€300', title: '', isSafeZone: false },
  { level: 2, prize: '€200', title: '', isSafeZone: false },
  { level: 1, prize: '€100', title: 'Cyber Smart Starter', isSafeZone: false },
];
